### ISSUE TITLE
Please release the ramp-workflow on pipy

### ISSUE THREAD

**Issue by GaelVaroquaux** [paris-saclay-cds/ramp-workflow#129]
For beginners, having to install from github means added difficulty. This package should really be released on pipy.

**Comment by jorisvandenbossche** [comment]
Agreed. The versioning is already in place with `versioneer`, so making a release is a matter of tagging (and then pushing to pypi of course). Next would be 0.3.0 (https://github.com/paris-saclay-cds/ramp-workflow/releases)

@glemaitre are there still things you think need to change for the autism challenge?

Anyhow, we can already release to make sure the process is clear.

**Comment by glemaitre** [comment]
I would merge the PR of the balanced accuracy
