### ISSUE TITLE
Requirement for ramp_test_submission

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-workflow#139]
It seems that we need something more from `ramp_test_submission` to be run:

https://github.com/ramp-kits/autism/issues/24

**Comment by glemaitre** [comment]
I assume this is something link to nbconvert or jupyter_client.
Since that we rely on `ramp_test_submission` should add those packages in the requirement rather than in the test-requirements?

**Comment by aboucaud** [comment]
Hmmm what I read from ramp-kits/autism#24 is
> `ramp_test_submission` works great 

and

>`ramp_test_notebook` gives me the following error:

You may have gotten confused between the two command lines.
`ramp_test_notebook` for the moment is only used for our own testing, thus with `testing-requirements.txt`. Of course people should be able to run it but to my knowledge, there is no incentive to do so anywhere.

**Comment by glemaitre** [comment]
ups I misread only saw `ramp_test_submission` so I am fine with doing nothing.
