### ISSUE TITLE
Couldn't re-order the score matrix..

### ISSUE THREAD

**Issue by kegl** [paris-saclay-cds/ramp-workflow#145]
We have an issue, I think it's after some pandas update. We cannot reorder the score matrix (train/test/valid, so lines), but for some people even the score columns are shuffled. @jorisvandenbossche could you look at it?

**Comment by jorisvandenbossche** [comment]
@kegl sorry, can you give a bit more context? Point to the code that is doing this, where you encounter this .. ?

**Comment by jorisvandenbossche** [comment]
OK, that's helpful, so it is about those lines of code:

https://github.com/paris-saclay-cds/ramp-workflow/blob/31d4037596db1526b5272343f273940d8912dc03/rampwf/utils/pretty_print.py#L44-L52

What versions of python, numpy and pandas are you using? 
I cannot reproduce any error with the combinations (py 3.5 / np 1.13 / pd master) and (py 3.5 / np 1.13 / pd 0.22)

**Comment by kegl** [comment]
python 2.7, pandas 0.23.1, numpy 1.12.1

**Comment by jorisvandenbossche** [comment]
It's your numpy version. The `np.isin` function used in the above snippet is new in numpy version 1.13. So it is actually not an update that broke this, but your (slightly) numpy version (although it is that we did not test that change for older numpy versions)
