### ISSUE TITLE
Refactor Predictions classes

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-workflow#168]
It is true that the factory `make_***` are doing the job somehow but the design of this module and more precisely of the specialized class is so surprising for a newcomer that we need to redesign them. We should only use inheritance. If the deal is that all those class need to be named `Predictions`, we just need to enforce that people import them for the specialized module `from rampwf.prediction_types import Predictions` and `Predictions` will inherit from `BasePrediction`.

**Comment by kegl** [comment]
Again, as with the scores, I would not change the features (specs). If you can get rid of `make_***`, fine, but I saw no other solution for including label names as class attirbutes (if I remember correctly). Why would a newcomer even have to know about how the prediction classes are created?

**Comment by kegl** [comment]
Again, I'd close this issue.

**Comment by agramfort** [comment]
Yes ok. No urgent need to change this
