### ISSUE TITLE
[RFC] Score refactoring

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-workflow#169]
Scores are defined as classes. IMO, this is an over-complicated design.

I think that those classes could be replaced by functions. If we want to keep the class first citizen then we could only do a wrapper to create classes from functions. What I am unsure is the impact on the backend to shift paradigm.

**Comment by glemaitre** [comment]
> currently higher is not always better for the scores and it allows to have multiple scores

Make it negative then :)

**Comment by agramfort** [comment]
I know :)

>

**Comment by kegl** [comment]
I would say don't touch something that's working fine. We have plenty features to implement. I wrapped sklearn's scores on purpose into classes to be able to have paramterizable scores and getting rid of that IMHO bad design negative RMSE (for example).

**Comment by kegl** [comment]
I'd close this issue for now.
