### ISSUE TITLE
[RFC] Decoupling the CV object of the main script

### ISSUE THREAD

**Issue by kegl** [paris-saclay-cds/ramp-workflow#184]
In complex workflows (for example in transfer learning or cascades) it may happen that `train_is` and `valid_is` that `problem.get_cv` yields are more complex than just a set of indices, and that the interaction between the data (returned by `problem.get_train_data`) and the CV fold object is more elaborate than just simple indexing. Furthermore, we may want to have different operations in `problem.workflow.test_submission` at training+validation time and test time.

1. At this time the [RAMP functional data flow](https://github.com/paris-saclay-cds/ramp-workflow/files/5089942/RAMP.functional.data.flow.pdf) contains an indexing step in the [main script](https://github.com/paris-saclay-cds/ramp-workflow/blob/b92ca38287c94124444f51f41d9231d0a94db3cc/rampwf/utils/submission.py#L185), between returning from `problem.workflow.test_submission` and entering into `Predictions.__init__`. The first change will be to pass the fold indices directly to `Predictions.__init__` and rewrite all existing Predictions to the default indexing. Then complex workflows can implement other interactions between the data and the CV fold in the customizable constructor.
2. We will optionally pass `fold=(train_is, valid_is)` to `problem.workflow.test_submission`. To keep backward compatibility, the main script will accept both `problem.workflow.test_submission(trained_workflow, X)` and `problem.workflow.test_submission(trained_workflow, X, fold)`.

The changes will be fully backward compatible, and will happen under the lid.

The new simplified and fully customizable [RAMP functional data flow](https://github.com/paris-saclay-cds/ramp-workflow/files/5089959/RAMP.functional.data.flow.1.pdf) reflects what will happen after the changes.

**Comment by kegl** [comment]
I will also add the data flow diagram to the doc and explain it there. It's long overdue to give some explanation to users who wish to implement their own workflows, and even to submitters who would like to know what happens under the lid.

**Comment by kegl** [comment]
#243

**Comment by kegl** [comment]
@lucyleeow @agramfort @glemaitre @maikia @albertcthomas any suggestion where to put the [data flow diagram](https://github.com/paris-saclay-cds/ramp-workflow/files/5089959/RAMP.functional.data.flow.1.pdf) and the explanation that goes with? I would put it either inside https://paris-saclay-cds.github.io/ramp-docs/ramp-workflow/stable/problem.html or right after, to explain how the elements in problem.py are used in the evaluation script. Would that be OK?

**Comment by agramfort** [comment]
yes. No objection on my side
