### ISSUE TITLE
Deploy documentation using CircleCI

### ISSUE THREAD

**Issue by lucyleeow** [paris-saclay-cds/ramp-workflow#188]
I would like to use CircleCI and `gh-pages` branch to deploy RAMP workflow documentation. The current version of the documentation can be found [here](https://7-91170031-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/index.html) - see #187 also.

This would involve adding a SSH key that allows CircleCI write access, so it can push to an orphan `gh-pages` branch. Full configurations steps can be found [here](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/). Any objections @agramfort @kegl ?

Note - ultimate goal will be to integrate the RAMP board and RAMP workflow documentation using the repo [ramp-docs](https://github.com/paris-saclay-cds/ramp-docs) as suggested by @glemaitre. This can be done later but the above suggestion will get the ramp documentation up for now.

**Comment by agramfort** [comment]
you have my  full support to help with the documentation of RAMP. thanks
heaps for taking this initiative.

>
