### ISSUE TITLE
CI - Switch from appveyor to azure pipeline

### ISSUE THREAD

**Issue by lucyleeow** [paris-saclay-cds/ramp-workflow#202]
Team management with appveyor is cumbersome and requires us to setup an account with appveyor (we haven't been using a team account, it was using @glemaitre's account and currently using @maikia's account). It has been suggested that we switch to Azure pipeline for our Windows tests. Any objections?

**Comment by glemaitre** [comment]
Actually you can also include the mac + linux in azure. It will be much faster than others. But it requires a bit of time to set it up. Maybe not a priority if we can see the output of appveyor even in Maria's account.

**Comment by lucyleeow** [comment]
@glemaitre I was actually just trying to fix the build icon on the README page. Following appveyors [guide](https://www.appveyor.com/docs/status-badges/#display-badge-for-specific-branch) it doesn't link to the most recent commit in rampworkflow/master but to @maikia's fork. There may be something that @maikia may be able to do though?

Alternatively I can just remove the badge from the README and we forget all about it...

**Comment by agramfort** [comment]
I would remove the badge

and stick to travis for mac and linux as it works

>

**Comment by glemaitre** [comment]
> and stick to travis for mac and linux as it works

Be aware that we might have users using Windows for ramp-wokflow. We need to be sure that it works for this platform as well.

For ramp-board we don't care.

**Comment by lucyleeow** [comment]
Appveyor is still being run. I am just removing the badge from the README as we can't seem to get it to work.

**Comment by glemaitre** [comment]
Goot with me.

**Comment by kegl** [comment]
We are using both linux and windows.
