### ISSUE TITLE
Avoid deprecation warning

### ISSUE THREAD

**Issue by albertcthomas** [paris-saclay-cds/ramp-workflow#204]
As the `imp` package is deprecated I suggest to now use `importlib` and change the [`import_file` function](https://github.com/paris-saclay-cds/ramp-workflow/blob/master/rampwf/utils/importing.py#L10) according to the [python doc](https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly).

Another possibility is to use the `runpy` module but this would imply to change the way the elements of a module are accessed.

**Comment by glemaitre** [comment]
More widely we should solve the issues which are raising Deprecation warning. We should have some stuff imported from `collections` instead of `collections.abc` as well.
