### ISSUE TITLE
Exception trace index in `print_submission_exception`

### ISSUE THREAD

**Issue by lucyleeow** [paris-saclay-cds/ramp-workflow#207]
Does anyone know what [this](https://github.com/paris-saclay-cds/ramp-workflow/blob/4bf2b0f0be205b9ff628e371961ab4df0d3e8ff5/rampwf/utils/io.py#L124) line in `print_submission_exception` is for?

```
    if trace[4].find('load_source') > -1:
        trace = trace[5:]
```
When I got an exception, there was a second exception which was that `trace[4]` was out of index (there were only 4 elements in `trace` not >=5). Why do we assume `trace` will be at least 5 elements?

**Comment by lucyleeow** [comment]
cc @agramfort @kegl @glemaitre

**Comment by agramfort** [comment]
git blame says it's @kegl who pushed this last year

>

**Comment by glemaitre** [comment]
I assume that it only prints the error message without the path to the kit avoiding people to know about the tree view of the computer. However, it seems that the size is wrong.

I would say that we should not assume 5 elements.

**Comment by kegl** [comment]
Yes, it was an attempt to cut the trace to see only the submission related part of the exception. The trace depth may be different in testing and in production.
