### ISSUE TITLE
Error when running `ramp-test`

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-workflow#218]
We are seeking for `./problem.py` while we should preprend the path to the submission kit.
Otherwise running `ramp-test` will fail if we are not in the kit directory which is annoying in `ramp-board` for the dispatcher.

**Comment by lucyleeow** [comment]
I can't seem to replicate the problem. We are looking in ` os.path.join(ramp_kit_dir, 'problem.py')` for the problem file:
```
def assert_read_problem(ramp_kit_dir='.'):
    # giving a random name to the module so it passes looped tests
    return import_module_from_source(
        os.path.join(ramp_kit_dir, 'problem.py'), 'problem'
    )
```

I can run:
```
ramp-test --ramp-kit-dir './iris' --ramp-data-dir './iris' --ramp-submission-dir './iris/submissions'
```
from outside the kit dir and it works. You do have to specify the data dir and submission dir, but I assume this was to offer flexibility, in case the submissions and data are not in the same dir as the kit dir.
@glemaitre

**Comment by glemaitre** [comment]
Uhm I might have mess-up then
