### ISSUE TITLE
Put the doc url in the readme

### ISSUE THREAD

**Issue by albertcthomas** [paris-saclay-cds/ramp-workflow#227]
Maybe it is just me but I had a hard time finding the doc url :). I would also add it to the readme.

**Comment by agramfort** [comment]
it's in the repo page url

+1 to add it to readme for example

anything that can help

>

**Comment by xuedong** [comment]
+1

**Comment by agramfort** [comment]
PR welcome

**Comment by albertcthomas** [comment]
Closing as fixed in PR #228
