### ISSUE TITLE
Keras and tensorflow testing requirements make CI fail

### ISSUE THREAD

**Issue by albertcthomas** [paris-saclay-cds/ramp-workflow#239]
`pip install keras` in the `testing-requirement.txt` installs the last version Keras 2.4 which requires tensorflow 2.2, whereas tensorflow 2.0.1 is specified in `testing-requirement.txt`. This is making CI fail, see PR #237.

We can either specify that we want keras<2.4 in the testing requirements of wait for  keras-team/keras#14129 to be resolved.

**Comment by cliffwoolley** [comment]
> We can either specify that we want keras<2.4 in the testing requirements of wait for keras-team/keras#14129 to be resolved.

If you need the older TensorFlow, you should pin your requirement to keras<2.4 .
