### ISSUE TITLE
requirements.txt in starting kits to specify dependencies

### ISSUE THREAD

**Issue by jorisvandenbossche** [paris-saclay-cds/ramp-workflow#25]
Proposal that each starting kit contains a `requirements.txt` file that specifies the packages and versions used.

To start with, this would be useful if you just want to run the starting kit and make sure you have the correct libraries installed (eg the pollinating insects notebook was written for keras 1.x, and you got errors if you had keras 2).

Later, this would maybe also be useful to give the ramp participant the ability to add things to the requirements file if he/she uses specific extra libraries in the submission (but then of course we need that the backend each time creates an env (or docker container) to run a submission).

**Comment by aboucaud** [comment]
Mandatory by default after merging #50.
