### ISSUE TITLE
BUG admin menu disappears when looking at the error

### ISSUE THREAD

**Issue by maikia** [paris-saclay-cds/ramp-workflow#256]
When admin clicks an error link (eg training error) on the `admin dashboard` or on `my submissions` they are redirected to the `error.txt` window. 
Here, the admins menu disappears and it is replaced by the regular users menu.  

Admins menu comes back if any other page is selected

**Comment by kegl** [comment]
Isn't this an https://github.com/paris-saclay-cds/ramp-board issue?

**Comment by maikia** [comment]
yes. You are of course right. I will change that
