### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-workflow#264]
Last release was in March 2020, and I think it would be good to make a new release before trying to merge the advanced branch.

There wasn't really much breaking changes since 0.3.3 but one year later 0.4.0 is still probably better than 0.3.4  

TODO: 

- [x] update changelog
- [x] likely include https://github.com/paris-saclay-cds/ramp-workflow/pull/245 

The other more major changes in https://github.com/paris-saclay-cds/ramp-workflow/pull/246 with potential backward compatibility implications could be included in a follow up 0.5.0 release

@glemaitre One everything is ready would you be able to upload it to PyPi? Otherwise I can do it, but I would need permissions (PyPi username: ryurchak).

**Comment by glemaitre** [comment]
Once this is ready, I can find time to make the upload to PyPI

**Comment by rth** [comment]
OK, I created the 0.4.0 tag and if I didn't mess up anything it should be good to go,
```
twine check dist/ramp_workflow-0.4.0-py3-none-any.whl 
Checking dist/ramp_workflow-0.4.0-py3-none-any.whl: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```
@glemaitre Could you also please change the symlink for the docs https://paris-saclay-cds.github.io/ramp-docs/ramp-workflow/dev/contribute.html#release-process ? Thanks!

**Comment by glemaitre** [comment]
yep

**Comment by glemaitre** [comment]
Done for both:

https://pypi.org/project/ramp-workflow/
https://paris-saclay-cds.github.io/ramp-docs/ramp-workflow/stable/

I also bump master to 0.5.0.dev0 and add the info in the "what's new"

**Comment by glemaitre** [comment]
Feel free to close the issue if we are good.

**Comment by rth** [comment]
Thanks @glemaitre!
