### ISSUE TITLE
Deprecation of add_javascript and add_stylesheet in Sphinx

### ISSUE THREAD

**Issue by albertcthomas** [paris-saclay-cds/ramp-workflow#278]
From Sphinx 4.0, we can no longer use `add_javascript` and `add_stylesheet`, they should be replaced by `add_js_file()` and `add_css_file()`. See https://www.sphinx-doc.org/en/master/extdev/deprecated.html

This is causing circle to fail, see #277 and #276.

Do we want to keep a sphinx version lower than 4? or should I go on with the change?

**Comment by rth** [comment]
I think for now, we could just pin sphinx to <4.0 as the release is recent I'm not sure that all sphinx plugins had time to migrate / make new compatible release. Then after a few months we could update the sphinx version.

Or update now, but one would need to visually compare the generated docs before/after to make sure nothing got broken. As you prefer.

**Comment by albertcthomas** [comment]
I'll pin sphinx to <4.0 for now, we can update it later.
