### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-workflow#300]
As mentioned by @kegl there is a number of changes on master that are still not released, so it would be good make a 0.5.0 release.

The only issue I see is that to be compatible with the server ramp-board would need https://github.com/paris-saclay-cds/ramp-board/pull/533 (I need to check what happened with the CI there).  But anyway, I think that it's not an issue, we could
 - release ramp-workflow now
 - then look into releasing ramp-board and updating the server.

Any objections?

**Comment by agramfort** [comment]
>
> As mentioned by @kegl <https://github.com/kegl> there is a number of
> changes on master that are still not released, so it would be good make a
> 0.5.0 release.
>
> The only issue I see is that to be compatible with the server ramp-board
> would need paris-saclay-cds/ramp-board#533
> <https://github.com/paris-saclay-cds/ramp-board/pull/533> (I need to
> check what happened with the CI there). But anyway, I think that it's not
> an issue, we could
>
>    - release ramp-worflow now
>    - then look into releasing ramp-board and updating the server.
>
> Any objections?
>

no objection. Just a remark the datacamp course runs till mid march and it
would be great to make sure
we don't break things during the challenge period. So if there is a risk
let's wait for the datacamp course
to finish

**Comment by rth** [comment]
The 0.5.0 release is done. The only thing is I don't have to update the `stable`  symlink in https://github.com/paris-saclay-cds/ramp-docs/tree/master/ramp-workflow . Could someone do that or give me permissions? Thanks.
