### ISSUE TITLE
BUG: scipy installation fails on travis with Python 2.7

### ISSUE THREAD

**Issue by aboucaud** [paris-saclay-cds/ramp-workflow#76]
This may be because we currently don't provide a version for `scipy` in the `setup.py`

Trouble is that it makes all the starting kit builds fail.

**Comment by jorisvandenbossche** [comment]
Where do you see it? The mars craters one is fine.

**Comment by aboucaud** [comment]
https://travis-ci.org/paris-saclay-cds/ramp-workflow/jobs/292615352

**Comment by jorisvandenbossche** [comment]
It's because of the new scipy release. They didn't upload the wheels yet

**Comment by jorisvandenbossche** [comment]
(so it is trying to build scipy from source, which is not that easy .. :-))

Possible solution if it is urgent is to pin scipy to 0.19, but I suppose somewhere during the day/night the wheels will be uploaded.

**Comment by aboucaud** [comment]
Working again..
